# Generated by Django 5.1.3 on 2024-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_watchlist_user_alter_forums_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
