# Generated by Django 5.1.3 on 2024-11-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_watchlist_image_url_watchlist_item_id_watchlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
    ]
