# Generated by Django 5.1.3 on 2024-12-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_pricehistory_itemname_pricehistory_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='price_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
